#!/bin/ksh
#help#
#************************************************************************************#
#                                                                                    #
# script to run CPTEC OPERATION                                                      #
# EnvironmentalVariablesMCGA.ksh    TQZZZZLXXX                                       #
#                                                                                    #
#                    ZZZZ   => 4 digits spectral resolution                          #
#                     XXX   => 3 digits vertical resolution                          #
#                                                                                    #
#************************************************************************************#
#help#

#
# Caminhos
#

# Caminho do BAM no HOME
export HOMEBASE=/lustre_xc50/joao_gerd/SMG/cptec/bam

# Caminho do BAM no scratchin (SUBMIT_HOME)
export SUBTBASE=/lustre_xc50/joao_gerd/SMG/datainout/bam

# Caminho do BAM no scratchout (SUBMIT_WORK)
export WORKBASE=/lustre_xc50/joao_gerd/SMG/datainout/bam

# Dados Externos
dadosExternos=/lustre_xc50/ioper/data/external

#
# Executáveis do BAM
#

export preEXEC=ParPre_MPI
export bamEXEC=ParModel_MPI
export posEXEC=ParPos_MPI

#
# Utilitarios
#

export caldate=${HOMEBASE}/utils/bin/caldate.3.0.1
export DIRGRADS=/opt/grads/2.0.a9/bin
export wgrib1=/cray_home/local/grads/grads-2.0.2.oga.2/bin/wgrib
export wgrib2=/cray_home/local/grib2/wgrib2/wgrib2
export inctime=${HOMEBASE}/../bin/inctime


#
# Variáveis do PBS
#

export QUOTA=CPTEC
export PBS_TUPA=eslogin13
export PBS_AUX=pesq
export HSTMAQ=$(uname -n)
export MAQUI=$(uname -s)


export tmstp=$(date +'%s')

