#!/bin/bash
#---------------------------------------------------------------------------------------------------#
#                         Brazilian global Atmospheric Model - BAM_V2.2.1                           #
#---------------------------------------------------------------------------------------------------#
#BOP                                                                                                #
# Descrição:                                                                                        #
#     Script para executar o pré-processamento do BAM                                               #
#                                                                                                   #
# Uso:                                                                                              #
#     ./runPre -t 299 -l 64 -I 2013010100                                                           #
#                                                                                                   #
#     ./runPre -t 299 -l 64 -np 800 -N 4 -d 10 -I 2020061900 -ti 574 -li 42 -s -G                   #
#                                                                                                   #
# Opções:                                                                                           #
#        * -t  <val> : truncamento [default: 62]                                                    #
#        * -l  <val> : numero de niveis [default: 28]                                               #
#        * -I  <val> : Data da condição inicial (cold start)                                        #
#        * -p  <val> : prefixo dos arquivos do BAM (condição inicial e previsões) [default: NMC]    #
#        * -np <val> : numero de processadores [default: 240]                                       #
#        * -N  <val> : numero de processadores por nós [default: 40]                                #
#        * -d  <val> : numero de Treads por processos MPI [default: 1]                              #
#        * -ti <val> : resolução espectral da análise de entrada no chopping [default: 1534]        #
#        * -li <val> : número de níveis vertivais da análise de entrada no chopping [default: 64]   #
#        * -n  <val> : Processos utilizados no pré-processamento [default: 0]:                      #
#                       * 0 - roda todos os processos                                               #
#                       * 1 - roda apenas alguns processos                                          #
#                       * 2 - para uso de debug                                                     #
#                       * 3 - roda processos necessários na assimilação de dados                    #
#        * -f  <val> : utiliza namelist customizado para rodar o pré. Sobrescreve  a opção -n       #
#        * -Gt <val> : Tipo de arquivo GDAS (Spec or Grid) [default: Grid]                          #
#        * -Gp <val> : Prefix do arquivo GDAS (gdas1, gdas, gblav) [default: gblav]                 #
#        * -s        : Suavização da topografia (default: off)                                      #
#        * -sp <val> : Percentagem para suavização de topografia [default: 0.12]                    #
#        * -A        : Escrever apenas arquivos de análise espectral para o BAM (default: off)      #
#        * -O        : Gera arquivo de ozonio [default: off]                                        #
#        * -T        : Gera arquivo de traçadores [default: off]                                    #
#        * -G        : Gera arquivo no formato GrADS [defaul: off]                                  #
#        * -Go       : Gera somente arquivo no formato GrADS [default: off]                         #
#        * -rm       : Remove arquivo GANL [default: off]                                           #
#        * -L        : Set Linear (on) or Quadratic Gaussian Grid (off) [default: off]              #
#                                                                                                   #
# Notas:                                                                                            #
#     * Até 14/Jan/2015 às 06Z (2015011406) as análises do NCEP estão na resolução TQ00574L064;     #
#       após esta data, as análises passam a ter a resolução TQ1534L064. A partir desta data, o     #
#       arquivo de temperatura da superfície do mar (TSM) lido é o                                  #
#       rtgssthr_grb_0.083.grib2.${DATA} (observe a resolução: 0.083 graus) e o arquivo de neve     #
#       (SNOW) não é mais lido (até 2015011400, eram lidos os arquivos gdas1.T00Z.sstgrb2.${DATA}   #
#       e gdas1.T00Z.sstgrb2.${DATA}). Outras informações sobre os novos arquivos de TSM:           #
#       http://www.nco.ncep.noaa.gov/pmb/products/sst/                                              #
#     * Até 19/Jul/2017 às 12Z (2017071912) as análises do NCEP estão no formato espectral, na      #
#       resolução TQ01534L064. A partir desta data, os arquivos de análise passam a serem           #
#       escritos em ponto de grade (utilizando-se a biblioteca nemsio) e o nome dos arquivos        #
#       passam a ser gdas.T${HH}Z.atmanl.nemsio.${DATA}, na mesma resolução. Outras informações     #
#       sobre as alterações dos modelos e produtos disseminados pelo NCEP:                          #
#       https://www.nco.ncep.noaa.gov/pmb/changes/                                                  #
#                                                                                                   #
# Revisões:                                                                                         #
#     * 22-06-2016: Khamis, E. G.    - código inicial                                               #
#     * 14-07-2016: Khamis, E. G.    - incluídas funções que tornam o runPre independente de        #
#                                      scripts externos através de um namelist                      #
#                                      no momento, continua dependente apenas do                    #
#                                      run_Chopping_parallel.bash e run_Chopping_serial.bash        #
#     * 21-07-2016: Khamis, E. G.    - runPre independente do run_Chopping_parallel.bash e          #
#                                      run_Chopping_serial.bash                                     #
#     * 26-07-2016: Khamis, E. G.    - inclusão de função que cria um script de submissão para      #
#                                      cada processo                                                #
#     * 28-07-2016: Khamis, E. G.    - mudança na forma de submissão dos processos e inclusão de    #
#                                      função de espera e checagem das saídas                       #
#                                      convém ressaltar que é feita uma busca de "ENDS NORMALLY"    #
#                                      no log do processo. alguns processos, como por exemplo       #
#                                      NormalModes e TopographyGradient, não possuem esse print no  #
#                                      código. esse print será incluído. quem for usar              #
#                                      esse script deverá recompilar o código Fortran com os        #
#                                      prints inclusos                                              #
#     * 20-09-2016: Bastarz, C. F.   - corrigida verificação do arquivo de análise quando a         #
#                                      suavização da topografia é realizada (PREFIXO=SMT)           #
#                                      corrigido o numero de processadores por nó do                #
#                                      Chopping_parralel (N=24)                                     #
#                                      generalizado o prefixo dos processos SSTClima,               #
#                                      FLUXCO2Clima, SSTWeekly, SSTMonthlyDirec, SSTDailyDirec      #
#                                      e TopographyGradient (modificacões feitas também no script   #
#                                      namelist.runPre)                                             #
#                                    - inclusao de testes e verificação da existência do arquivo    #
#                                      de SST                                                       #
#     * 17-02-2020: Bastarz, C. F.   - revisão geral para a consolidação da versão e algumas        #
#                                      melhorias                                                    #
#     * 10-03-2020: Bastarz, C. F.   - inclusão do processo CO2MonthlyDirec                         #
#     * 09-09-2020: Khamis, E. G.    - adaptação do novo pré na estrutura do BAM v1.4.0             #
#     * 20-04-2021: Khamis, E. G.    - adaptação do novo pré na estrutura do BAM v2.2.1             #
#     * 19-05-2021: de Mattos, J. G. - refatoração do script                                        #
#     * 12-08-2021: de Mattos, J. G. - inclusão de opção para namelist externo.
# TODO:                                                                                             #
#     * validar a funcao fileout para checar as saidas                                              #
#     * incluir numero de processadores e processadores por no' na linha de comando                 #
#                                                                                                   #
# DIMNT/CGCT/INPE, 2021                                                                            #
#EOP                                                                                                #
#---------------------------------------------------------------------------------------------------#
#

WhereIam=$(dirname ${BASH_SOURCE})

# Incluindo funcoes genericas
. ${WhereIam}/runPre.func

#
# Definindo local de execucao deste script
#

basepath=$(whereami)

#
# Obtendo variáveis de ambiente do BAM
#

. ${WhereIam}/EnvironmentalVariables

#
# define some paths
#

dirExec=${SUBTBASE}/pre/exec
dirData=${SUBTBASE}/pre/datain

#
# Parse command line options
#
verbose='.FALSE.'
args=${@} #save arguments temporarily
while (( $# )); do
   opt=$1
   case ${opt} in
       -t) TRC=$2; shift 2;; # shift twice [p.e. -t 299 ]
       -l) LV=$2; shift 2;;
       -I) LABELI=$2; shift 2;;
       -p) PREFIX=$2; shift 2;;
      -np) MPITasks=$2; shift 2 ;;
       -N) TasksPerNode=$2; shift 2;;
       -d) ThreadsPerMPITask=$2; shift 2;;
      -ti) TRCinp=$2; shift 2;;
      -li) LVinp=$2; shift 2;;
       -n) NMLOPT=$2; shift 2;;
      -Gt) GDASType=$2; shift 2;;
      -Gp) GDASPrefix=$2; shift 2;;
       -s) SmoothTopo='.TRUE.'; shift 1;; # shift once [p.e. -s]
      -sp) SmthPerCut=$2; shift 2;;
       -A) GDASOnly='.TRUE.'; shift 1;;
       -O) GetOzone='.TRUE.'; shift 1;;
       -T) GetTracers='.TRUE.'; shift 1;;
       -G) GrADS='.TRUE.'; shift 1;;
      -Go) GrADSOnly='.TRUE.'; shift 1;;
      -rm) rmGANL='.TRUE.'; shift 1;;
       -v) verbose='.TRUE.';shift 1;;
       -f) nmlFile=$2; shift 2;;
       -h) usage $0 ; exit 0;;
       *) echo -e "\033[31;1mWarning:\033[m Unknown argument:\033[33;1m $opt\033[m"; shift 1;;
   esac
done
set -- $args #restore arguments

if [ ${verbose} = '.TRUE.' ];then
   echo -e "running :: \033[33;1m$0\033[m \033[33;1m$@\033[m"
fi

# truncamento
if [ -z ${TRC} ];then
   TRC=62
fi

# numero de niveis verticais
if [ -z ${LV} ];then
   LV=28
fi

# prefixo dos arquivos
if [ -z ${PREFIX} ];then
   PREFIX=NMC
fi

# Data da Condição Inicial (cold start)
if [ -z ${LABELI} ];then
      echo -e "\033[31;1m LABELI not set \033[m"
      echo -e ""
      echo -e "for help try:"
      echo -e ""
      echo -e "${0} -h "
      echo -e ""
      exit 1
fi

# truncamento de arquivo de entrada
if [ -z ${TRCinp} ];then
   TRCinp=1534
fi

# numero de niveis verticais do arquivo de entrada
if [ -z ${LVinp} ];then
   LVinp=64
fi

# Numero de processadores que serao utilizados no Job
if [ -z ${MPITasks} ];then
   MPITasks=240
fi

# Numero de processadores utilizados por tarefas MPI
if [ -z ${TasksPerNode} ];then
   TasksPerNode=40
fi

# Number of cores hosting OpenMP threads
if [ -z ${ThreadsPerMPITask} ]; then
   ThreadsPerMPITask=1
fi

# Topography Smoothing 
if [ -z ${SmoothTopo} ];then
   SmoothTopo='.FALSE.'
fi

# Percentagem para suavização de topografia [default: 0.12]
if [ -z ${SmthPerCut} ];then
   SmthPerCut=0.12
fi

# GDAS only write 
if [ -z ${GDASOnly} ];then
   GDASOnly='.FALSE.'
fi

# Process option
if [ -z ${NMLOPT} ];then
   NMLOPT=0
fi

# Prefix do arquivo GDAS (gdas1, gdas, gblav) [default: gdas1]
# esta parte esta automatica
# veja getAnlNCEP
#if [ -z ${GDASPrefix} ];then
#   GDASPrefix='gblav'
#fi

# Tipo de arquivo GDAS (spec or grid) [default: grid]
if [ -z ${GDASType} ];then
   GDASType='Netcdf'
fi

# Gera arquivo de ozonio [default: off]
if [ -z ${GetOzone} ];then
   GetOzone='.FALSE.'
fi
# Gera arquivo de traçadores [default: off]
if [ -z $GetTracers ];then
   GetTracers='.FALSE.'
fi

# Gera arquivo no formato GrADS [defaul: off]
if [ -z ${GrADS} ];then
   GrADS='.FALSE.'
fi

# Gera somente arquivo no formato GrADS [default: off]
if [ -z ${GrADSonly} ];then
   GrADSOnly='.FALSE.'
fi

# Remove arquivo GANL [default: off]  
if [ -z ${rmGANL} ];then
   rmGANL='.FALSE.'
fi
# Set Linear (on) or Quadratic Gaussian Grid (off) [default: off]
if [ -z ${SetLinear} ];then
   SetLinear='.FALSE.'
fi
#
# 
#
echo -e "\033[34;1m Running BAM Pre-process for \033[m\033[32;1m${LABELI}\033[m"

#-----------------------------------------------------------------------------#
# Some sanity checks
#
# Esta parte está automatica 
# veja getAnlNCEP
#
#GDAStype and GDASprefix
#if [ ${GDASType} = 'grid' ];then
#   if  [ ${GDASPrefix} != 'gdas' -a ${GDASPrefix} != 'gblav' ];then 
#      echo -e "\033[31;1m ERROR:\033[m "
#      echo -e "Quando GDASType='grid'"
#      echo -e "GDASPrefix deve ser 'gdas' ou gblav"
#      echo -e ""
#      echo "GDASType=${GDASType}; GDASPrefix=${GDASPrefix}" 
#      exit 1
#  fi
#fi
#
#if [ ${GDASType} = 'spec' ];then
#   if  [ ${GDASPrefix} != 'gdas1' -a ${GDASPrefix} != 'gblav' ];then 
#      echo -e "\033[31;1m ERROR:\033[m "
#      echo -e "Quando GDASType='grid'"
#      echo -e "GDASPrefix deve ser 'gdas1' ou gblav"
#      echo -e ""
#      echo "GDASType=${GDASType}; GDASPrefix=${GDASPrefix}" 
#      exit 1
#  fi
#fi

# Prefix with smoothTopo on
if [ ${SmoothTopo} = '.TRUE.' ];then
   echo -e "\033[32;1m SmoothTopo = ${SmoothTopo}\033[m"
   echo -e "\033[32;1m set PREFIX = \033[m\033[31;1m SMT\033[m"
   PREFIX=SMT
fi

# end sanity checks
#-----------------------------------------------------------------------------#

# Get BAM sizes

getBAMSize ${TRC}
if [ $? -ne 0 ];then
   exit $?
fi

#Spectral Resolution Cut Off for Topography Smoothing
MendCut=$(echo $TRC | awk '{ print (int(1/((5+(40000/($1*3)))*(3/(40000)))) +1) }')

#-----------------------------------------------------------------------------#
# Parse NameList to get Pre-processes
if [ -z ${nmlFile} ];then

   case ${NMLOPT} in
      0|geral) nml=geral;;
      1|  opt) nml=opt;;
      2|debug) nml=debug;;
      3|  das) nml=das;;
      4|  chp) nml=chp;;
            *) echo -e "\033[31;1m Lista de processos desconhecida:\033[m \`-n ${NMLOPT}\`"
               echo -e "for help try:"
               echo -e "${0} -h"
               exit 1;;
   esac
   echo ""
   echo -e "\033[33;1mlist of processes that will be executed\033[m"
   echo ""
   modulesToRun=''
   while read -r opt name; do
   
      assign $name $opt
   
      if [ ${opt} -eq 0 ];then
         echo -en "[\033[31;1mNOT\033[m] "
      elif [ ${opt} -eq 1 ];then
         echo -en "[\033[32;1mRUN\033[m] "
         modulesToRun+=\'$name\',
      fi
      echo -e "${name}"
   done < <(sed -n "/^${nml}:/,/^::/{/^${nml}:/d;/^::/d;p}" ${basepath}/runPre.nml)

else

   echo ""
   echo -e "\033[33;1mlist of processes that will be executed\033[m"
   echo ""
   modulesToRun=''
   while read -r opt name; do
   
      assign $name $opt
   
      if [ ${opt} -eq 0 ];then
         echo -en "[\033[31;1mNOT\033[m] "
      elif [ ${opt} -eq 1 ];then
         echo -en "[\033[32;1mRUN\033[m] "
         modulesToRun+=\'$name\',
      fi
      echo -e "${name}"
   done < <(sed -n "/^:/,/^::/{/^:/d;/^::/d;p}" ${nmlFile})

fi

# get NCEP anl
if [ ${Chopping} -eq 1 ];then
   getAnlNCEP ${LABELI} ${GDASPrefix}
   STATUS=$?
   if [ $STATUS -ne 0 ];then
      echo -e "\033[31;1m Nenhum arquivo de Análise encontrado para o dia:\033[m \033[32;1m${LABELI}\033[m"
      exit $STATUS
   fi
   
   if [ ${GDASPrefix} = 'gdas' -a -z ${GDASType} ];then
      GDASType='Netcdf'
   fi

   if [ ${GDASPrefix} = 'gdas1' -a -z ${GDASType} ];then
      GDASType='spec'
   fi

   if [ ${GDASPrefix} = 'gblav' ];then
      echo -e "\033[31;1m >>>> WARNNING <<<<\033[m"
      echo -e " Using \033[33;1m gblav \033[m anl file"
      echo -e " GDASType was set as:\033[33;1m ${GDASType^}\033[m"
      echo -e "\033[33;1m Is this correct?\033[m"      
      echo -e "\033[31;1m >>>>>>>>><<<<<<<<<\033[m"
   fi

fi

# get SST files
if [ ${SSTWeekly} -eq 1 ];then
   getSST ${LABELI}
   STATUS=$?
   if [ $STATUS -ne 0 ];then
      echo -e "\033[31;1m Nenhum arquivo de SST encontrado para o dia:\033[m \033[32;1m${LABELI}\033[m"
      exit $STATUS
   fi
fi

# get SoilMoisture files
if [ ${SoilMoistureWeekly} -eq 1 ];then
   getSoilFiles ${LABELI}
   STATUS=$?
   if [ $STATUS -ne 0 ];then
      echo -e "\033[31;1m Nenhum arquivo de Umidade do Solo encontrado para o dia:\033[m \033[32;m${LABELI}\033[m"
      exit $STATUS
   fi
fi


#
#-----------------------------------------------------------------------------#
# Parse Pre_run.nml
#
sed -e "s;#MODULESTORUN#;${modulesToRun};g" \
    -e "s;#dirdata#;${SUBTBASE};g"           \
    -e "s;#IM#;$IM;g"                       \
    -e "s;#JM#;$JM;g"                       \
    -e "s;#RESOUT#;${TRC};g"                \
    -e "s;#KMOUT#;${LV};g"                  \
    -e "s;#RESO#;${TRC};g"                  \
    -e "s;#RESIN#;${TRCinp};g"              \
    -e "s;#KMIN#;${LVinp};g"                \
    -e "s;#GetOzone#;${GetOzone};g"         \
    -e "s;#GetTracers#;${GetTracers};g"     \
    -e "s;#GrADS#;${GrADS};g"               \
    -e "s;#GrADSOnly#;${GrADSOnly};g"       \
    -e "s;#GDASOnly#;${GDASOnly};g"         \
    -e "s;#SmoothTopo#;${SmoothTopo};g"     \
    -e "s;#RmGANL#;${rmGANL};g"             \
    -e "s;#PREFIXO#;$PREFIX;g"              \
    -e "s;#DataGDAS#;${GDASType^};g"        \
    -e "s;#AnlPref#;${GDASPrefix};g"        \
    -e "s;#DATA#;${LABELI};g"               \
    -e "s;#MendCut#;$MendCut;g"             \
    -e "s;#SmthPerCut#;$SmthPerCut;g"       \
    -e "s;#SetLinear#;${SetLinear};g"       \
    -e "s;!.*;;g"                           \
    -e "s;^ \+;;g"                          \
    -e "/^[\s\t]*$/d"                       \
    ${basepath}/PRE_run.nml_default > ${dirExec}/PRE_run.nml

# get PRE_cfg.nml
if [ ${nml} = 'das' ];then
   cp -pfr ${basepath}/PRE_cfg.nml_das ${dirExec}/PRE_cfg.nml 
else
   cp -pfr ${basepath}/PRE_cfg.nml_default ${dirExec}/PRE_cfg.nml
fi
sed -i "s;#nproc#;${MPITasks};g" ${dirExec}/PRE_cfg.nml

files=(sstmtd.nml sstdld.nml sstssd.nml co2mtd.nml)
for file in ${files[@]};do
   sed "s;#dirdata#;${SUBTBASE};g" ${basepath}/${file}_default > ${dirExec}/${file}
done

# submit Pre-process
echo -ne "\033[34;1m Running Pre-processes \033[m"
labelOut=${LABELI}_${tmstp}
submitPre ${MPITasks} ${TasksPerNode} ${ThreadsPerMPITask} ${labelOut}
status=$?
if [ $status -eq 0 ];then
   echo -e "\033[34;1m [\033[m\033[32;2m OK \033[m\033[34;1m]\033[m"
   cat ${dirExec}/saida_${labelOut}.txt | grep -i warning | sort -u
   exit $status
else
   echo -e "\033[34;1m[\033[m\033[31;1m Fail \033[m\033[34;1m]\033[m"
   cat ${dirExec}/saida_${labelOut}.txt | grep -i error | sort -u
   cat ${dirExec}/saida_${labelOut}.txt | grep -i warning | sort -u 
   exit $status
fi


